services:
  app:
    image: 'mindcare-backend:latest'
    build:
      context: .
    container_name: springboot-api
    ports:
      - "8080:8080"
    networks:
      - springcloud
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mindcare_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - JWT_SECRET=0C/ZZj9OCW7Q74lUM200BayaFq6u12EKyps4NLFQNufowubX5nE1DQT8XRdwv0zUBp7Tns1DQT8XRdwv0zUBp7Tns1yhYlwzUCm3maQkg==
      - APP_CORS_ALLOWED_ORIGINS=http://54.80.210.120,http://54.80.210.120:4200
      - IP_FRONTEND=http://54.80.210.120
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: postgres-db
    networks:
      - springcloud
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=mindcare_db
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  springcloud:
    name: springcloud
